version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Seoul
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - 'type:chore'
    open-pull-requests-limit: 2
